name: exam_6_replay
description: This project is written for re-submission of Module 6

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/ic_images/
    - assets/translations/


  fonts:
    - family: SF_PRO
      fonts:
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sf_pro/SF-Pro-Display-Semibold.otf
          weight: 600
